"""Evaluator that scores a released Doc-to-LoRA (D2L) checkpoint on needle-in-a-haystack
(NIAH) tasks, out-of-process under the upstream D2L environment (``upstream/doc-to-lora/
.venv``): ``ctx_to_lora`` pins its own torch/transformers/peft/vllm stack (see SETUP.md).
This module never imports ``ctx_to_lora`` directly - it shells out to
``scripts/run_d2l_eval.py`` and reads back the JSON manifest it writes.

Design fork (see PROJECT_PLAN.md/AGENTS instructions for context): every other setting in
this repo splits a ``HypernetworkBackend.generate()`` step (produce a portable adapter
artifact) from a ``DownstreamEvaluator.evaluate()`` step (score an already-generated
artifact against a frozen interpreter). D2L does not support that split. Its forward pass
(``ctx_to_lora.modeling.hypernet.ModulatedPretrainedModel``) is a hand-rolled, non-PEFT
monkeypatch: per-document LoRA deltas are generated by ``generate_weights()``, immediately
merged into the running model's ``down_proj`` layers by ``combine_lora()``/
``lora_forward_packed()``, and consumed inline during ``generate()`` - they are never
written to disk as a standalone adapter directory the way ``hyper_llm_modulator.save_lora``
does for Text-to-LoRA. ``ctx_to_lora.eval_utils.evaluate()`` (which ``run_eval`` wraps)
bakes tokenization, per-document generation, and scoring into one call per dataset name,
and does not expose a separable "generate a reusable artifact" step anywhere in its public
API. Reproducing that split here would mean either (a) reimplementing pieces of D2L's
hand-rolled modeling internals just to extract an intermediate tensor nobody else needs, or
(b) faking an ``AdapterArtifact`` that no downstream evaluator could actually load - both
worse than just modeling the real shape of the upstream API. So this module instead
exposes a single class, ``ReleasedDocToLoRANIAHEvaluator``, whose one public method shells
out once and returns ``EvaluationResult``s directly. It deliberately does not subclass
``HypernetworkBackend`` or ``DownstreamEvaluator`` (``contracts.py``) - its natural
inputs (a checkpoint path plus a list of ``ctx_magic_number_<lo>_<hi>`` dataset names) and
outputs (D2L's own per-dataset ROUGE-L/F1 metrics) don't fit either ABC's method signature
without distorting one side or the other.
"""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import time
from typing import Sequence

from .contracts import EvaluationResult

REPO_ROOT = Path(__file__).resolve().parents[2]
UPSTREAM_D2L_DIR = REPO_ROOT / "upstream" / "doc-to-lora"
UPSTREAM_D2L_PYTHON = UPSTREAM_D2L_DIR / ".venv" / "bin" / "python"
EVAL_SCRIPT = REPO_ROOT / "scripts" / "run_d2l_eval.py"


class ReleasedDocToLoRANIAHEvaluator:
    """Wraps a released D2L ``pytorch_model.bin`` checkpoint; each ``evaluate*`` call is
    one subprocess invocation of ``scripts/run_d2l_eval.py`` covering every requested
    ``ctx_magic_number_<lo>_<hi>`` dataset (D2L's own ``eval_utils.evaluate()`` already
    loads the checkpoint once and iterates datasets internally, so there is no benefit to
    a persistent-process/streaming bridge the way ``VLLMDownstreamEvaluator`` needs one -
    there is exactly one model load per call regardless of how many datasets are passed).
    """

    def __init__(
        self,
        checkpoint: str | Path,
        trial_id: str,
        max_ctx_chunk_len: int = 1024,
        max_new_tokens: int = 32,
        eval_batch_size_gen: int = 4,
        python: str | Path = UPSTREAM_D2L_PYTHON,
    ):
        self.checkpoint = Path(checkpoint)
        self.trial_id = trial_id
        self.max_ctx_chunk_len = max_ctx_chunk_len
        self.max_new_tokens = max_new_tokens
        self.eval_batch_size_gen = eval_batch_size_gen
        self.python = Path(python)
        if not self.python.exists():
            raise FileNotFoundError(
                f"upstream doc-to-lora interpreter not found at {self.python}; "
                "see SETUP.md to provision the upstream/doc-to-lora uv venv"
            )
        if not self.checkpoint.exists():
            raise FileNotFoundError(f"checkpoint not found: {self.checkpoint}")

    def _run(
        self,
        datasets: Sequence[str],
        split: str,
        limit: int,
        output_dir: Path,
        checkpoint_path: Path | None,
        model_name_or_path: str | None,
        remove_context: bool,
    ) -> dict:
        output_dir = Path(output_dir).resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
        args = [
            str(self.python),
            str(EVAL_SCRIPT.resolve()),
            "--datasets",
            *datasets,
            "--split",
            split,
            "--max-samples-per-ds",
            str(limit),
            "--max-ctx-chunk-len",
            str(self.max_ctx_chunk_len),
            "--max-new-tokens",
            str(self.max_new_tokens),
            "--eval-batch-size-gen",
            str(self.eval_batch_size_gen),
            "--output-dir",
            str(output_dir),
        ]
        if checkpoint_path is not None:
            args += ["--checkpoint-path", str(checkpoint_path.resolve())]
        else:
            args += ["--model-name-or-path", model_name_or_path]
        if remove_context:
            args.append("--remove-context")

        started = time.perf_counter()
        # Do NOT .resolve() the interpreter path: it is a symlink into the upstream venv,
        # and fully resolving it collapses to the real system interpreter, which skips
        # venv site-package activation (same gotcha as ReleasedTextToLoRABackend).
        subprocess.run(args, check=True, cwd=UPSTREAM_D2L_DIR)
        subprocess_wall_seconds = time.perf_counter() - started

        manifest = json.loads((output_dir / "manifest.json").read_text())
        manifest["subprocess_wall_seconds"] = subprocess_wall_seconds
        return manifest

    def _results_from_manifest(self, manifest: dict, adapter: str, split: str) -> list[EvaluationResult]:
        results = []
        for split_name, dataset_metrics in manifest["metrics"].items():
            task_id = split_name[len(f"{split}_") :] if split_name.startswith(f"{split}_") else split_name
            f1_key = f"{split_name}_rougeL.f1"
            n_key = f"{split_name}_num_samples_rougeL.f1"
            results.append(
                EvaluationResult(
                    trial_id=self.trial_id,
                    task_id=task_id,
                    split=split,
                    adapter=adapter,
                    metrics={
                        "rougeL_f1": dataset_metrics.get(f1_key, float("nan")),
                        "n_examples": float(dataset_metrics.get(n_key, 0)),
                    },
                    generated_parameter_count=0,
                    generation_seconds=0.0,
                    inference_seconds=manifest["eval_seconds"],
                    metadata={
                        "checkpoint": manifest["checkpoint"],
                        "base_model": manifest["base_model"],
                        "remove_context": manifest["remove_context"],
                        "peak_gpu_memory_bytes": manifest["peak_gpu_memory_bytes"],
                        "subprocess_wall_seconds": manifest["subprocess_wall_seconds"],
                        "torch": manifest["torch"],
                        "raw_metrics": dataset_metrics,
                    },
                )
            )
        return results

    def evaluate(
        self, datasets: Sequence[str], limit: int, output_dir: Path, split: str = "test", adapter: str = "lora_r8_d2l"
    ) -> list[EvaluationResult]:
        """Generate the per-document LoRA internally and score it - the "treatment" row."""
        manifest = self._run(
            datasets,
            split,
            limit,
            output_dir,
            checkpoint_path=self.checkpoint,
            model_name_or_path=None,
            remove_context=False,
        )
        return self._results_from_manifest(manifest, adapter, split)

    def evaluate_frozen(
        self,
        datasets: Sequence[str],
        limit: int,
        output_dir: Path,
        model_name_or_path: str,
        split: str = "test",
        remove_context: bool = True,
    ) -> list[EvaluationResult]:
        """Frozen-interpreter baseline: the base model with no hypernetwork at all.
        ``remove_context=True`` (the default) withholds the document entirely, matching
        this repo's other settings' ``frozen_interpreter`` baseline (no adapter, no
        context) - pass ``remove_context=False`` for an ``interpreter_with_icl``-style
        baseline that hands the document to the base model directly in its prompt instead
        of internalizing it via a generated LoRA.
        """
        manifest = self._run(
            datasets,
            split,
            limit,
            output_dir,
            checkpoint_path=None,
            model_name_or_path=model_name_or_path,
            remove_context=remove_context,
        )
        adapter = "frozen_interpreter" if remove_context else "interpreter_with_icl"
        return self._results_from_manifest(manifest, adapter, split)
